Repository Neovici/cosmoz-bottom-bar, pull requests merged in 2020-10, with the labels that each got.

#84 Feature/83 resize observer
  cosmoz-bottom-bar-view.js
  cosmoz-bottom-bar.js
  demo/bottom-bar-match-parent.html
  demo/bottom-bar-view.html
  demo/bottom-bar.html
  demo/helpers/x-view.js
  package-lock.json
  package.json
  test/cosmoz-bottom-bar-view.test.js
  test/cosmoz-bottom-bar.test.js
Labels: enhancement

#89 feat: distribute via slots
  cosmoz-bottom-bar-view.js
  cosmoz-bottom-bar.html.js
  cosmoz-bottom-bar.js
Labels: bug

#91 fix: prevent resize observer loops
  cosmoz-bottom-bar.js
Labels: enhancement

#90 fix: disabled buttons in the menu are not styled
  cosmoz-bottom-bar.html.js
Labels: enhancement

#88 Restore cosmoz-bottom-bar-view & cosmoz-bottom-bar behaviors
  cosmoz-bottom-bar-view.js
  cosmoz-bottom-bar.html.js
  cosmoz-bottom-bar.js
  lib/use-bottom-bar-view.js
  shell.nix
  test/cosmoz-bottom-bar-view.test.js
  test/cosmoz-bottom-bar.test.js
Labels: bug, enhancement
